# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

r:
  - 3.3
  - devel
  - release
  
 install:
  - Rscript -e 'install.packages("quanteda", repos = "http://cran.rstudio.com")'