language: r
sudo: false
cache: packages
  
matrix:
    include:
        - os: linux
          sudo: required
          r: release
        - os: linux
          sudo: required
          r: oldrel
        - os: osx
          r: release


script:
  - Rscript -e "install.packages(c('devtools', 'quanteda'), type = 'source')" # can not be found on older versions of R
  - R CMD build .
  - R CMD check *tar.gz
