language: r
dist: xenial
cache: packages

matrix:
    include:
      - os: linux
        sudo: required
        r: release
      - os: linux
        sudo: required
        r: oldrel
        before_install:
          - Rscript -e 'install.packages("remotes");remotes::install_version("statnet.common", version = "4.1.4")' # oldrel needs a special version
      - os: linux
        sudo: required
        r: devel
      - os: osx
        r: release
        brew_packages: poppler
        before_install:
          - brew install libgit2
# not supported yet
#      - os: windows
#        r: release

r_packages:
  - covr

-addons:
  apt:
    packages:
      - libpoppler-cpp-dev

script:
    - R CMD build .
    - R CMD check *tar.gz
    
after_success:
    - Rscript -e 'covr::codecov(type = "tests")'
