language: r
sudo: false
cache: packages

os:
  - linux
  - osx

r:
  #- devel
  - release
  - oldrel

script:
  - Rscript -e "install.packages('quanteda')" # can not be found on older versions of R
  - R CMD build .
  - R CMD check *tar.gz
