language: r
sudo: false
cache: packages
  
matrix:
    include:
        - os: linux
          sudo: required
          r: release
        - os: linux
          sudo: required
          r: oldrel
        - os: osx
          r: release

before_install:
    - Rscript -e 'install.packages(c("devtools", "quanteda"))' # needs to be installed for every version separatly

script:
    - R CMD build .
    - R CMD check *tar.gz
