language: r
dist: xenial
cache: packages
  
matrix:
    include:
      - os: linux
        sudo: required
        r: release
      - os: linux
        sudo: required
        r: oldrel
      - os: linux
        sudo: required
        r: devel
      - os: osx
        r: release
        brew_packages: poppler
        before_install:
          - brew install libgit2

r_packages:
  - covr
  
addons:
  apt:
    packages:
      - libpoppler-cpp-dev

script:
    - R CMD build .
    - R CMD check *tar.gz
    
after_success:
  - Rscript -e 'library(covr);codecov()'
