language: r
sudo: false
cache: packages
  
matrix:
    include:
        - os: linux
          sudo: required
          r: release
        - os: linux
          sudo: required
          r: oldrel
        - os: linux
          sudo: required
          r: devel
        - os: osx
          r: release

before_install:
    - Rscript -e 'install.packages(c("devtools", "quanteda"))' # needs to be installed for every version separatly
    - Rscript -e 'remotes::install_version("statnet.common", version = "4.1.4")' # oldrel needs a special version

r_github_packages:
    - r-lib/covr

script:
    - R CMD build .
    - R CMD check *tar.gz
    
after_success:
  - Rscript -e 'R.Version();covr::codecov()'
